hytech-racing/code-2020

- Utilities/bms_util_LTC6804-2/bms_util_LTC6804-2.ino
User need not input a number (7) before (m/M) now, they can view menu from the start
> Fixed the menu

- Utilities/current_monitor/current_monitor.ino
I wrote this utility to measure the charge we put back into the accumulator after FH2019.
> Current monitoring utility for use with coulomb counting

- Utilities/main_control_unit_testing/Main_Control_Unit_Testing.ino
Made the changes as requested. 
Got rid of the `|` in places where it'll be hard to parse, replaced it with spaces instead. Got rid of the `debug` boolean flag and replaced it with `dashboard_btn_testing` and `pedal_input_testing` wherever necessary. Added a new boolean variable `torque_debugging` to take care of the parts of the code dealing with code that can be used for debugging.
> Ecu low voltage testing

- .github/pull_request_template.md
Adds a new PR template based on the ones from `circuits-2020` and `circuits-support-2020`.
> Adds PR template for code

- LICENSE
- README.md
https://choosealicense.com/licenses/gpl-3.0/
> Creates LICENSE

- Vehicle/Telemetry_Control_Unit/Telemetry_Control_Unit.ino
Reverts hytech-racing/code-2020#26 (can't find evidence of whatever error this was supposed to fix)
> Revert "IC ID telemetry fix"

- Telemetry/SD_cpp/can_msg_def.h
- Telemetry/SD_cpp/makefile
- Telemetry/SD_cpp/sd_reader.cpp
Converts MC faults from fault code to explicit flag names.
Validated E2E in Spring but never merged.
- - [x] Did you *use CPU Speed = 76 Mhz and Optimize = Faster* when testing?
- - [x] Did you *check for merge conflicts*?
- - [x] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
> Add MC Faults to SD Parser

- Telemetry/SD_cpp/can_msg_def.h
- Vehicle/Telemetry_Control_Unit/Telemetry_Control_Unit.ino
Reverts hytech-racing/code-2020#28
A bunch of stuff went missing. Code won't compile as is.
> Revert "Wheel speed cleanup"

- Telemetry/.gitignore
- Telemetry/telemetry_aws/csv_server.js
- Telemetry/telemetry_aws/csv_to_influx.py
- Telemetry/telemetry_aws/db.py
- Telemetry/telemetry_aws/mqtt_server.py
- Telemetry/telemetry_aws/package.json
- Telemetry/telemetry_aws/readme.md
- Telemetry/telemetry_aws/views/index.html
- Telemetry/telemetry_aws/views/status.html
- Vehicle/Xbee_LTE/mqttconverter.py
Separated out all the telemetry code from the wheel speed / whatever else was tangled up in it.
I don't think I typed anything new, it was just moving specific files to a new branch.
> InfluxDB cleanup

- Telemetry/telemetry_py/console_config.py
- Telemetry/telemetry_py/telemetry_lte_xbee.py
I made this thing in Spring, it makes it WAY easier to add new messages to the telemetry_lte_xbee dashboard. DO NOT MERGE unless influxdb-cleanup has been merged, as this branch is dependent on that one
Tested it out E2E in Spring.
> Telemetry Console Refactor

- Simulator/src/core/Simulator.cpp
- Simulator/test/CMakeLists.txt
> Fix teardown error

- Libraries/HyTech_CAN/BMS_voltages.h
- Telemetry/autoparse/app/mqtt_server.py
- Telemetry/autoparse/exe/console
- Telemetry/autoparse/exe/influx_server
- Telemetry/autoparse/exe/parse_folder
- Telemetry/autoparse/exe/setup.sh
- Telemetry/autoparse/exe/upload
Autoparse bug fixes
Tested locally
*Put any additional datasheets, information, and/or useful links here.*
> Execute from anywhere

- Libraries/VehicleUtilities/VariableLED.h
Allow PWM output to variable LED
No testing
analogWrite(0) == digitalWrite(LOW)
analogWrite(255) == digitalWrite(HIGH)
https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/wiring_analog.c
> Allow pwm output to variable LEDs

- Telemetry/autoparse/README.md
- Telemetry/autoparse/app/parser.cpp
- Telemetry/autoparse/include/Writer.h
- Telemetry/autoparse/src/Writer.cpp
- Telemetry/autoparse/templates/AutoParse.h
- Telemetry/autoparse/user/CustomFunctions.cpp
Adding -v flag will now disable difference checking in runtime.
*Put any additional datasheets, information, and/or useful links here.*
> Create verbose mode for autoparse

- .gitignore
> add csv to gitignore

- Telemetry/autoparse/Makefile
- Telemetry/autoparse/app/parser.cpp
Arvind made these changes, I tested on my windows using WSL
*Describe how you tested the contents of the pull request. Describe how each major …
> made autoparse compatible with mac

- Vehicle/BMS_Control_Unit/BMS_Control_Unit.ino
> HV now compiles

- Vehicle/Dashboard/Dashboard.ino
- Vehicle/Main_Control_Unit/MCU_rev10_dfs.h
- Vehicle/Main_Control_Unit/Main_Control_Unit.ino
> Final lv code

- Playground/pragma_pack/pod_check.cpp
> added pod data check

- Vehicle/Main_Control_Unit/Main_Control_Unit.ino
- Vehicle/Main_Control_Unit_rev10_testing/Main_Control_Unit_rev10_testing.ino
> Updated torque modes for endurance

- Telemetry/telemetry_aws/db.py
> telem console torque mode derived from dashboard

- Telemetry/telemetry_aws/db.py
> torque mode console revert
